'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';

const TEAM = [
  {
    name: 'Alex Johnson',
    role: 'Project Lead & Full Stack Developer',
    initials: 'AJ',
    color: 'from-violet-500 to-purple-600',
    bg: 'bg-violet-100 dark:bg-violet-900/30',
    text: 'text-violet-700 dark:text-violet-300',
    contributions: ['System Architecture', 'Database Design', 'API Development'],
    github: '#',
    linkedin: '#',
  },
  {
    name: 'Priya Sharma',
    role: 'Frontend Developer & UI/UX Designer',
    initials: 'PS',
    color: 'from-pink-500 to-rose-600',
    bg: 'bg-pink-100 dark:bg-pink-900/30',
    text: 'text-pink-700 dark:text-pink-300',
    contributions: ['UI Components', 'Responsive Design', 'User Experience'],
    github: '#',
    linkedin: '#',
  },
  {
    name: 'Rahul Verma',
    role: 'AI/ML Engineer',
    initials: 'RV',
    color: 'from-blue-500 to-cyan-600',
    bg: 'bg-blue-100 dark:bg-blue-900/30',
    text: 'text-blue-700 dark:text-blue-300',
    contributions: ['AI Integration', 'Prompt Engineering', 'OpenRouter API'],
    github: '#',
    linkedin: '#',
  },
  {
    name: 'Sneha Patel',
    role: 'Backend Developer & DevOps',
    initials: 'SP',
    color: 'from-emerald-500 to-teal-600',
    bg: 'bg-emerald-100 dark:bg-emerald-900/30',
    text: 'text-emerald-700 dark:text-emerald-300',
    contributions: ['Vercel Deployment', 'Supabase Setup', 'Auth & Security'],
    github: '#',
    linkedin: '#',
  },
  {
    name: 'Aryan Gupta',
    role: 'Database Engineer & QA',
    initials: 'AG',
    color: 'from-amber-500 to-orange-600',
    bg: 'bg-amber-100 dark:bg-amber-900/30',
    text: 'text-amber-700 dark:text-amber-300',
    contributions: ['Prisma Schema', 'Testing & QA', 'Documentation'],
    github: '#',
    linkedin: '#',
  },
];

const TECH_STACK = [
  { name: 'Next.js 15', icon: '▲', desc: 'App Router, Server Actions' },
  { name: 'React 19', icon: '⚛', desc: 'UI Components, Hooks' },
  { name: 'Prisma ORM', icon: '◆', desc: 'Type-safe Database Queries' },
  { name: 'Supabase', icon: '⚡', desc: 'PostgreSQL Database' },
  { name: 'Clerk Auth', icon: '🔐', desc: 'Authentication & Users' },
  { name: 'OpenRouter AI', icon: '🤖', desc: 'AI Model API Gateway' },
  { name: 'Inngest', icon: '⏱', desc: 'Background Job Scheduling' },
  { name: 'Tailwind CSS', icon: '🎨', desc: 'Utility-first Styling' },
  { name: 'Vercel', icon: '▴', desc: 'Edge Deployment Platform' },
];

const AI_FEATURES = [
  {
    icon: '💬',
    title: 'AI Career Coach Chatbot',
    desc: 'Personalized career advice powered by DeepSeek AI via OpenRouter. Knows your industry, skills, and experience to give you tailored guidance.',
  },
  {
    icon: '📄',
    title: 'AI Resume Builder',
    desc: 'Generate professional, ATS-optimized resumes with AI assistance. Get real-time feedback and scoring.',
  },
  {
    icon: '✉️',
    title: 'Cover Letter Generator',
    desc: 'Craft compelling cover letters tailored to specific job descriptions using advanced language models.',
  },
  {
    icon: '🎯',
    title: 'Mock Interview Prep',
    desc: 'Industry-specific interview questions generated by AI, with instant feedback and improvement tips.',
  },
  {
    icon: '📊',
    title: 'Industry Insights Dashboard',
    desc: 'Real-time market data, salary trends, and skill demand forecasts — all AI-generated and updated weekly.',
  },
];

export default function AboutUs() {
  const [activeTeamMember, setActiveTeamMember] = useState(null);
  const [scrollY, setScrollY] = useState(0);
  const progressRef = useRef(null);
  const heroRef = useRef(null);

  useEffect(() => {
    const handleScroll = () => {
      const pct = (window.scrollY / (document.body.scrollHeight - window.innerHeight)) * 100;
      if (progressRef.current) progressRef.current.style.width = pct + '%';
      setScrollY(window.scrollY);
    };

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('animate-in');
          }
        });
      },
      { threshold: 0.1 }
    );

    document.querySelectorAll('.reveal').forEach((el) => observer.observe(el));
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <>
      <style>{`
        .reveal { opacity: 0; transform: translateY(24px); transition: all 0.6s cubic-bezier(0.22,1,0.36,1); }
        .reveal.animate-in { opacity: 1; transform: translateY(0); }
        .reveal-delay-1 { transition-delay: 0.1s; }
        .reveal-delay-2 { transition-delay: 0.2s; }
        .reveal-delay-3 { transition-delay: 0.3s; }
        .reveal-delay-4 { transition-delay: 0.4s; }
        .card-hover { transition: transform 0.3s ease, box-shadow 0.3s ease; }
        .card-hover:hover { transform: translateY(-4px); }
        .gradient-text { background: linear-gradient(135deg, #6366f1, #8b5cf6, #a855f7); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }
        .grid-bg { background-image: linear-gradient(rgba(99,102,241,0.05) 1px, transparent 1px), linear-gradient(90deg, rgba(99,102,241,0.05) 1px, transparent 1px); background-size: 40px 40px; }
        .shimmer { background: linear-gradient(90deg, transparent, rgba(255,255,255,0.08), transparent); background-size: 200% 100%; animation: shimmer 3s infinite; }
        @keyframes shimmer { 0% { background-position: -200% 0; } 100% { background-position: 200% 0; } }
        .float { animation: float 6s ease-in-out infinite; }
        .float-delay { animation: float 6s ease-in-out infinite 2s; }
        @keyframes float { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(-10px); } }
        .badge-pulse { animation: pulse 2s infinite; }
        @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.6; } }
      `}</style>

      {/* Progress Bar */}
      <div className="fixed top-0 left-0 z-50 h-0.5 bg-gradient-to-r from-violet-500 to-purple-500 transition-all duration-100" ref={progressRef} style={{ width: '0%' }} />

      <div className="min-h-screen bg-background">

        {/* Hero */}
        <section ref={heroRef} className="relative overflow-hidden grid-bg pt-32 pb-20 px-4">
          <div className="absolute inset-0 bg-gradient-to-b from-violet-500/5 via-transparent to-transparent" />

          {/* Floating orbs */}
          <div className="absolute top-20 left-10 w-64 h-64 rounded-full bg-violet-500/10 blur-3xl float" />
          <div className="absolute bottom-10 right-10 w-96 h-96 rounded-full bg-purple-500/8 blur-3xl float-delay" />

          <div className="relative container mx-auto max-w-4xl text-center">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-violet-500/30 bg-violet-500/10 text-violet-400 text-xs font-medium mb-6 badge-pulse">
              <span className="w-1.5 h-1.5 rounded-full bg-violet-400 inline-block" />
              Capstone Project — Semester 2
            </div>

            <h1 className="text-5xl md:text-7xl font-bold mb-6 leading-tight">
              Behind the{' '}
              <span className="gradient-text">Build</span>
            </h1>

            <p className="text-muted-foreground text-lg md:text-xl max-w-2xl mx-auto mb-10 leading-relaxed">
              PathPilot is an AI-powered career development platform built by 5 second-semester students
              as their Capstone-1 project. Here's the story of how we built it.
            </p>

            <div className="flex flex-wrap justify-center gap-4">
              <Link href="/dashboard">
                <button className="px-6 py-3 rounded-xl bg-violet-600 hover:bg-violet-700 text-white font-medium transition-all duration-200 hover:scale-105">
                  Try PathPilot →
                </button>
              </Link>
              <a href="https://github.com" target="_blank" rel="noopener noreferrer">
                <button className="px-6 py-3 rounded-xl border border-border hover:bg-muted font-medium transition-all duration-200">
                  View Source Code
                </button>
              </a>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-3 gap-6 mt-16 max-w-lg mx-auto">
              {[
                { num: '5', label: 'Team Members' },
                { num: '9+', label: 'Technologies' },
                { num: '5', label: 'AI Features' },
              ].map((s) => (
                <div key={s.label} className="text-center reveal">
                  <div className="text-3xl font-bold gradient-text">{s.num}</div>
                  <div className="text-xs text-muted-foreground mt-1">{s.label}</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* AI Career Coach Feature Highlight */}
        <section className="py-20 px-4 bg-gradient-to-b from-violet-500/5 to-transparent">
          <div className="container mx-auto max-w-5xl">
            <div className="reveal text-center mb-12">
              <span className="text-violet-400 text-sm font-medium uppercase tracking-wider">Star Feature</span>
              <h2 className="text-3xl md:text-4xl font-bold mt-2 mb-4">AI Career Coach Assistant</h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                Our flagship feature — a personalized AI chatbot that knows your profile, industry, and skills
                to give you career advice that actually makes sense for you.
              </p>
            </div>

            <div className="grid md:grid-cols-2 gap-6 mb-8">
              <div className="reveal reveal-delay-1 rounded-2xl border border-violet-500/20 bg-violet-500/5 p-6 card-hover">
                <div className="text-4xl mb-4">🤖</div>
                <h3 className="font-semibold text-lg mb-2">How it works</h3>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li className="flex items-start gap-2"><span className="text-violet-400 mt-0.5">✓</span> Reads your profile — industry, skills, experience, bio</li>
                  <li className="flex items-start gap-2"><span className="text-violet-400 mt-0.5">✓</span> Passes it as context to DeepSeek AI via OpenRouter</li>
                  <li className="flex items-start gap-2"><span className="text-violet-400 mt-0.5">✓</span> Gives personalized, actionable career guidance</li>
                  <li className="flex items-start gap-2"><span className="text-violet-400 mt-0.5">✓</span> Available on every page via floating chat button</li>
                </ul>
              </div>

              <div className="reveal reveal-delay-2 rounded-2xl border border-purple-500/20 bg-purple-500/5 p-6 card-hover">
                <div className="text-4xl mb-4">⚡</div>
                <h3 className="font-semibold text-lg mb-2">What it can do</h3>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li className="flex items-start gap-2"><span className="text-purple-400 mt-0.5">✓</span> Resume tips tailored to your industry</li>
                  <li className="flex items-start gap-2"><span className="text-purple-400 mt-0.5">✓</span> Interview preparation strategies</li>
                  <li className="flex items-start gap-2"><span className="text-purple-400 mt-0.5">✓</span> Skill gap analysis and learning roadmaps</li>
                  <li className="flex items-start gap-2"><span className="text-purple-400 mt-0.5">✓</span> Salary negotiation advice</li>
                </ul>
              </div>
            </div>

            {/* AI Features Grid */}
            <div className="grid md:grid-cols-3 gap-4">
              {AI_FEATURES.map((f, i) => (
                <div key={f.title} className={`reveal reveal-delay-${(i % 4) + 1} rounded-xl border border-border bg-card p-5 card-hover`}>
                  <span className="text-2xl mb-3 block">{f.icon}</span>
                  <h4 className="font-semibold text-sm mb-1">{f.title}</h4>
                  <p className="text-xs text-muted-foreground leading-relaxed">{f.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Team Section */}
        <section className="py-20 px-4">
          <div className="container mx-auto max-w-5xl">
            <div className="reveal text-center mb-12">
              <span className="text-violet-400 text-sm font-medium uppercase tracking-wider">The Builders</span>
              <h2 className="text-3xl md:text-4xl font-bold mt-2 mb-4">Meet Our Team</h2>
              <p className="text-muted-foreground max-w-xl mx-auto">
                5 passionate 2nd semester students who turned a capstone project into a fully deployed AI platform.
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
              {TEAM.map((member, i) => (
                <div
                  key={member.name}
                  role="button"
                  tabIndex={0}
                  aria-expanded={activeTeamMember === i}
                  className={`reveal reveal-delay-${(i % 4) + 1} rounded-2xl border border-border bg-card p-6 card-hover cursor-pointer transition-all duration-300 focus:outline-none focus-visible:ring-2 focus-visible:ring-violet-400 ${activeTeamMember === i ? 'ring-2 ring-violet-500/50' : ''}`}
                  onClick={() => setActiveTeamMember(i)}
                  onKeyDown={(event) => {
                    if (event.key === 'Enter' || event.key === ' ') {
                      event.preventDefault();
                      setActiveTeamMember(i);
                    }
                  }}
                >
                  {/* Avatar */}
                  <div className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${member.color} flex items-center justify-center text-white font-bold text-lg mb-4`}>
                    {member.initials}
                  </div>

                  <h3 className="font-semibold text-base mb-0.5">{member.name}</h3>
                  <p className="text-xs text-muted-foreground mb-4">{member.role}</p>

                  {/* Contributions */}
                  <div className="flex flex-wrap gap-1.5">
                    {member.contributions.map((c) => (
                      <span key={c} className={`text-xs px-2 py-0.5 rounded-full ${member.bg} ${member.text} font-medium`}>
                        {c}
                      </span>
                    ))}
                  </div>

                  <div className="mt-4 pt-4 border-t border-border min-h-[2.5rem]">
                    <div className={`flex gap-3 transition-opacity duration-300 ${activeTeamMember === i ? 'opacity-100' : 'opacity-0 pointer-events-none'}`} aria-hidden={activeTeamMember !== i}>
                      <a href={member.github} onClick={(event) => event.stopPropagation()} className="text-xs text-muted-foreground hover:text-foreground transition-colors">GitHub →</a>
                      <a href={member.linkedin} onClick={(event) => event.stopPropagation()} className="text-xs text-muted-foreground hover:text-foreground transition-colors">LinkedIn →</a>
                    </div>
                  </div>
                </div>
              ))}

              {/* Team vibe card */}
              <div className="reveal reveal-delay-2 rounded-2xl border border-dashed border-violet-500/30 bg-violet-500/5 p-6 flex flex-col justify-center items-center text-center">
                <div className="text-4xl mb-3">🚀</div>
                <h3 className="font-semibold mb-2">Built in Semester 2</h3>
                <p className="text-xs text-muted-foreground leading-relaxed">
                  From idea to deployed product — PathPilot was designed, built, and shipped as our Capstone-1 project.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Tech Stack */}
        <section className="py-20 px-4 bg-gradient-to-b from-transparent to-violet-500/5">
          <div className="container mx-auto max-w-5xl">
            <div className="reveal text-center mb-12">
              <span className="text-violet-400 text-sm font-medium uppercase tracking-wider">Under the Hood</span>
              <h2 className="text-3xl md:text-4xl font-bold mt-2 mb-4">Tech Stack</h2>
              <p className="text-muted-foreground max-w-xl mx-auto">
                Modern, production-grade technologies chosen for performance, scalability, and developer experience.
              </p>
            </div>

            <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
              {TECH_STACK.map((tech, i) => (
                <div key={tech.name} className={`reveal reveal-delay-${(i % 4) + 1} flex items-center gap-4 rounded-xl border border-border bg-card p-4 card-hover`}>
                  <div className="w-10 h-10 rounded-lg bg-muted flex items-center justify-center text-lg flex-shrink-0">
                    {tech.icon}
                  </div>
                  <div>
                    <div className="font-semibold text-sm">{tech.name}</div>
                    <div className="text-xs text-muted-foreground">{tech.desc}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="py-20 px-4">
          <div className="container mx-auto max-w-2xl text-center reveal">
            <div className="rounded-3xl border border-violet-500/20 bg-gradient-to-br from-violet-500/10 to-purple-500/5 p-12">
              <div className="text-5xl mb-6">🎓</div>
              <h2 className="text-3xl font-bold mb-4">Try PathPilot</h2>
              <p className="text-muted-foreground mb-8 leading-relaxed">
                Experience the AI career tools we built. Get personalized advice, build your resume,
                and prepare for interviews — all powered by AI.
              </p>
              <Link href="/dashboard">
                <button className="px-8 py-3.5 rounded-xl bg-violet-600 hover:bg-violet-700 text-white font-medium transition-all duration-200 hover:scale-105">
                  Get Started Free →
                </button>
              </Link>
            </div>
          </div>
        </section>

      </div>
    </>
  );
}